[2024-02-12T13:51:23.209+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Weather_DAG_V4.12.data_to_db scheduled__2024-02-12T00:06:00+00:00 [queued]>
[2024-02-12T13:51:23.289+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Weather_DAG_V4.12.data_to_db scheduled__2024-02-12T00:06:00+00:00 [queued]>
[2024-02-12T13:51:23.294+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-12T13:51:23.410+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): data_to_db> on 2024-02-12 00:06:00+00:00
[2024-02-12T13:51:23.426+0000] {standard_task_runner.py:60} INFO - Started process 18441 to run task
[2024-02-12T13:51:23.462+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Weather_DAG_V4.12', 'data_to_db', 'scheduled__2024-02-12T00:06:00+00:00', '--job-id', '10249', '--raw', '--subdir', 'DAGS_FOLDER/Weather_dag.py', '--cfg-path', '/tmp/tmp64xs8irq']
[2024-02-12T13:51:23.470+0000] {standard_task_runner.py:88} INFO - Job 10249: Subtask data_to_db
[2024-02-12T13:51:23.949+0000] {task_command.py:423} INFO - Running <TaskInstance: Weather_DAG_V4.12.data_to_db scheduled__2024-02-12T00:06:00+00:00 [running]> on host 06573eafe810
[2024-02-12T13:51:24.649+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Weather_DAG_V4.12' AIRFLOW_CTX_TASK_ID='data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-02-12T00:06:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-12T00:06:00+00:00'
[2024-02-12T13:51:24.651+0000] {postgres.py:172} INFO - Running copy expert: COPY weather_tab FROM STDIN, filename: weather.csv
[2024-02-12T13:51:24.672+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-02-12T13:51:24.741+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-12T13:51:24.825+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=Weather_DAG_V4.12, task_id=data_to_db, execution_date=20240212T000600, start_date=20240212T135123, end_date=20240212T135124
[2024-02-12T13:51:24.945+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-12T13:51:24.982+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
